### ISSUE TITLE
ModuleNotFoundError: No module named 'repositories.midas'

### ISSUE THREAD

**Issue by Neklioz** [Extraltodeus/multi-subject-render#10]
I installed the extension via the extensions tab, followed everything and I'm getting this error

I guess I only need to put midas on the repositories folder, but nothing of this is on the readme, so I wanted to write it here to check if this is the problem and should be on the readme or not, nice work!

**Comment by Extraltodeus** [comment]
Normally when you restart the UI it installs midas. Reloading the UI (maybe twice). Might just to the trick. Otherwise git clone the midas repository from your webui folder.

**Comment by Neklioz** [comment]
Then I guess it is because I only reloaded the webui one time, thanks!

**Comment by Extraltodeus** [comment]
did it work?

**Comment by Neklioz** [comment]
I'm having the same error #9 has, im using txt2img, I'm not sure why but tried to reinstall and it's still giving the same problem

**Comment by Extraltodeus** [comment]
Try just doing a git pull from your webui folder. Then delete the midas folder in your webui/repositories. Then restart it all.

**Comment by chiowa** [comment]
having same issue, tried git cloning and pulling midas too. restarting webui several times didnt work either.

**Comment by Extraltodeus** [comment]
I mean git pull to update your webui.

Then delete the midas folder and this extension.

Then install it from the webui.

**Comment by Neklioz** [comment]
I keep having the same error, yes, there is a midas folder, at first I did a git pull from midas repository, deleted it and restarted the webui to get it installed manually too, nothing works

![image](https://user-images.githubusercontent.com/57619097/203985987-2384ee25-0df7-4586-bc3f-b39feda6754a.png)

![image](https://user-images.githubusercontent.com/57619097/203986087-089833dc-3eb3-47e5-9ce2-c9f8b65be40c.png)

**Comment by Extraltodeus** [comment]
What's your python version?

python --version
in a command line

**Comment by Extraltodeus** [comment]
were you able to make it work?

**Comment by Neklioz** [comment]
Hello, sorry for leaving this. I couldn't until right now, had to do a clean install of the webui, so I'm not sure why I couldn't before as it was up to date
