### ISSUE TITLE
ModuleNotFoundError: No module named 'repositories.midas'

### ISSUE THREAD

**Issue by DrMacabre** [Extraltodeus/multi-subject-render#16]
Hello, i'm getting this error when generating a new image.
Installed in webui from the extensions tab

ModuleNotFoundError: No module named 'repositories.midas'

**Comment by Extraltodeus** [comment]
could you check in that solved issue if anything in there could solve your problem? Sorry to not be giving more info right now I'm on mobile :)

**Comment by Extraltodeus** [comment]
forgot the link lol
https://github.com/Extraltodeus/multi-subject-render/issues/10

**Comment by DrMacabre** [comment]
the midas folder is just missing from the repositories. I'd rather not reinstall the webui now, do you have a link i could pull it from?

**Comment by Extraltodeus** [comment]
git clone https://github.com/Extraltodeus/multi-subject-render.git extensions/multi-subject-render

from your webui folder

**Comment by DrMacabre** [comment]
thanks, i meant the midas repository which is missing in my install. i remember installing it with pip install midas when using SD webui  with python the first time but i'm using VOC now and have no idea how to execute the pip install with it

**Comment by DrMacabre** [comment]
Nevermind, i've tried outside of VOC and it loaded everything. Gonna brought this to the attention of Softology
