### ISSUE TITLE
typo(?)

### ISSUE THREAD

**Issue by yuuki76** [Extraltodeus/multi-subject-render#21]
`treshold`, isn't it a mistake for `threshold`?
https://github.com/Extraltodeus/multi-subject-render/blob/fceaa6c15d0fe7c21818d7ad30f3f6a8f41517f7/scripts/multirender.py#L63

**Comment by Extraltodeus** [comment]
Yes :')

**Comment by Extraltodeus** [comment]
d7cb1205e2d834debc78f9448d4e6220415db604

**Comment by yuuki76** [comment]
thanks
