### ISSUE TITLE
firstphase_width'

### ISSUE THREAD

**Issue by dizziglizzi** [Extraltodeus/multi-subject-render#34]
Whenever I try to use this I get an AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'firstphase_width' error. I'm not very techy so I have no idea what this means or how to fix it. I tried using the default settings and also messed around trying out different settings but I always get the same error

**Comment by xarathos517** [comment]
Came here about the same issue. My best guess is this is because of the changes to hires fix in webUI but I can't be sure.

**Comment by Hecatonchires667** [comment]
Hi everyone,

when i try to do anything with the script and try to do anything... nothing works.
I just get the following error:

"AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'firstphase_width' "

Or a bit more detailled:
scripts\multirender.py", line 190, in run o_firstphase_width = p.firstphase_width AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'firstphase_width'

Anyone an idea what to do?

Thx a lot :)

**Comment by Croestalker** [comment]
I'm dumb, what do I do to fix this error?
