### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by jpentland** [Extraltodeus/multi-subject-render#40]
When running any settings with the script I get a "list index out of range" error and no output is created

Stable diffusion version: python: 3.7.13  •  torch: 1.13.0+rocm5.2  •  xformers: N/A  •  gradio: 3.15.0  •  commit: 4cc02ec7

Running in docker on linux, with AMD Rx5700XT card.

Multi-subject render updated today Jan 12

Settings used:

Everything default with the background prompt "lake". In the subject field three lines with "man" "woman" "dog" respectively. In the final prompt "woman and a man with their dog at a lake".

Console output: 

```
+ python -u launch.py --api --medvram --no-half --precision=full --listen --enable-insecure-extension-access --opt-split-attention
100%|██████████| 20/20 [00:09<00:00,  2.21it/s]
DDIM Sampler: 100%|██████████| 25/25 [00:11<00:00,  2.12it/s]
DDIM Sampler: 100%|██████████| 25/25 [00:07<00:00,  3.19it/s]
DDIM Sampler: 100%|██████████| 25/25 [00:07<00:00,  3.18it/s]
Error completing request
Arguments: ('lake ', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 4, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, False, False, '', 1, '', 0, '', True, False, False, 'woman\nman\ndog', 5, 24, 12.5, 1000, 'DDIM', 0, 64, 64, 'woman and a man with their dog at a lake', 64, 7.5, 0.42, 'DDIM', 64, 64, 1, 0, 92, True, True, True, False, False, False, 'midas_v21_small') {}
Traceback (most recent call last):
  File "/dockerx/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/dockerx/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/dockerx/stable-diffusion-webui/modules/txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "/dockerx/stable-diffusion-webui/modules/scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "/dockerx/stable-diffusion-webui/extensions/multi-subject-render/scripts/multirender.py", line 231, in run
    p.prompt    = foregen_prompts[i] if len(foregen_prompts) > 1 else foregen_prompt
IndexError: list index out of range
```

**Comment by WildBanjos** [comment]
So I was having this issue too. However, I double checked the readme instructions, and it turns out the "Number of foreground images" needs to equal the number of intended subjects.

![image](https://user-images.githubusercontent.com/117058715/213962344-1673fdb3-00c5-41f8-86e5-b7e84c438dac.png)
![image](https://user-images.githubusercontent.com/117058715/213962414-d30ba252-e3d9-469b-91da-091ed2c0dcef.png)

After updating that value to match the line/subject count, the script finished generation without issue.
