### ISSUE TITLE
How to achieve best result?

### ISSUE THREAD

**Issue by enzyme69** [Extraltodeus/multi-subject-render#46]
I might need some guidance on getting best result.

STEP 1
I understand we prompting the background. I tried 1600 x 512, but some model does not work. I ended using just 512 x 512, and it will stretch.

STEP 2
I manage to get okey result, sometimes with variation of face (if person), but STEP 3 seems to make all the faces look the same again somewhat.

STEP 3
Final step blending is the weird one, although it seems to unify everything, I tend to get low quality result. I wonder if I need to increase the steps.

When specifying 1600 x 512 in STEP 3, it works, but it took 30 minutes on Mac Mini M2 Pro.

**Comment by Extraltodeus** [comment]
Well the big resolution should only be for the final step indeed since the subjects are usually smaller than the final blend.

Now I'm sorry but high resolution with stable diffusion does take time. If your computer can not manage these res, do like me and use colab!
