### ISSUE TITLE
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'sampler_name'

### ISSUE THREAD

**Issue by FormerTwitterEmployee** [Extraltodeus/multi-subject-render#9]
Sorry if this isn't an issue with your code directly. The process keeps getting interrupted with this error. I've used SD quite a bit by now, never seen it before. Am I using the wrong ckpt perhaps? 

`Traceback (most recent call last):
  File "C:\Users\***\stable-diffusion-webui\modules\ui.py", line 185, in f 
    res = list(func(*args, **kwargs))` 

  `File "C:\Users\***\stable-diffusion-webui\webui.py", line 56, in f 
    res = func(*args, **kwargs)` 

  `File "C:\Users\***\stable-diffusion-webui\modules\txt2img.py", line 45, in txt2img 
    processed = modules.scripts.scripts_txt2img.run(p, *args)` 

  `File "C:\Users\***\stable-diffusion-webui\modules\scripts.py", line 297, in run 
    processed = script.run(p, *script_args)` 

  `File "C:\Users\***\stable-diffusion-webui\extensions\multi-subject-render\scripts\multirender.py", line 167, in run 
    o_sampler_name = p.sampler_name`

**Comment by Extraltodeus** [comment]
Are you using it in img2img? Since I did not made that script for that, I kinda forgot to make it not appear in that tab.

**Comment by FormerTwitterEmployee** [comment]
so I can only use it in img2img then? I was using it in regular txt2img mode

**Comment by Extraltodeus** [comment]
It is made for txt2img. Try reinstalling the extension (delete it's folder in the extension folders). I had that bug like yesterday so maybe you have the older version?

**Comment by Extraltodeus** [comment]
Ohhhh! I think I know. Update your AUTOMATIC1111 installation (just git pull from the main folder)

That's a recent update.

**Comment by FormerTwitterEmployee** [comment]
I updated and I think it's working. Just need to read the manual about 100 times to get things to look good. Thanks for the help.
